name: Kali Linux via Docker - Long Running RustDesk

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    name: Start Long-Running Kali Container...
    runs-on: ubuntu-latest # We run Docker on top of Ubuntu
    # Set timeout slightly less than the maximum (usually 360 mins = 6 hours)
    # to ensure clean shutdown messages if it hits the limit.
    timeout-minutes: 355

    steps:
      - name: Checkout Code (Optional)
        uses: actions/checkout@v4
        # Add this if you have helper scripts in your repo

      - name: Run Kali Container, Install & Start RustDesk, Keep Alive
        run: |
          echo "Starting Kali Linux container..."
          docker run --rm -i --name kali-rustdesk \
            kalilinux/kali-rolling \
            /bin/bash -c '
            echo "Inside Kali container. Updating apt..."
            export DEBIAN_FRONTEND=noninteractive # Prevent interactive prompts
            apt-get update -y

            echo "Installing prerequisites (wget, ca-certificates, libraries)..."
            # Add any other dependencies RustDesk might need on a bare Kali image
            # Ensure all graphical dependencies are met if expecting GUI interaction (difficult)
            apt-get install -y wget ca-certificates libgtk-3-0 libxcb-randr0 libxfixes3 libxdamage1 libxcursor1 libxinerama1 libxcomposite1 libxi6 libxtst6 libasound2 libdbus-1-3 libcairo2

            echo "Downloading RustDesk..."
            # !!! You should still verify this URL manually if the script fails !!!
            RUSTDESK_URL=$(curl -s https://api.github.com/repos/rustdesk/rustdesk/releases/latest | grep browser_download_url | grep "amd64.deb" | cut -d '"' -f 4 | head -n 1)
            if [ -z "$RUSTDESK_URL" ]; then
              echo "Failed to automatically find RustDesk URL. Please update the script."
              exit 1
            fi
            echo "Found URL: $RUSTDESK_URL"
            wget -O rustdesk-installer.deb "$RUSTDESK_URL"

            echo "Installing RustDesk (Attempt 1)..."
            apt-get install -y ./rustdesk-installer.deb
            INSTALL_EXIT_CODE=$? # Capture exit code of the first install attempt

            # Check if the first install failed (non-zero exit code)
            if [ $INSTALL_EXIT_CODE -ne 0 ]; then
                echo "Initial RustDesk install failed (Code: $INSTALL_EXIT_CODE). Attempting to fix broken dependencies..."
                apt --fix-broken install -y
                echo "Retrying RustDesk installation (Attempt 2)..."
                apt-get install -y ./rustdesk-installer.deb
                # Check if the second install attempt failed
                if [ $? -ne 0 ]; then
                   echo "RustDesk install failed even after fixing dependencies. Exiting."
                   exit 1
                fi
            fi

            echo "RustDesk install process completed."

            echo "Attempting to retrieve RustDesk connection info..."
            # !!! Configuration for ID/Password is CRITICAL and likely needs specific commands !!!
            echo "Attempting to find ID in config (best effort):"
            # Ensure config directory exists before grep, although RustDesk install might create it
            mkdir -p ~/.config/RustDesk
            grep "id = " ~/.config/RustDesk/RustDesk*.toml || echo "ID not found in default config (RustDesk might need to run once)."

            echo "Attempting to start RustDesk service in the background..."
            rustdesk --service &
            sleep 10

            echo "Re-checking for ID after attempting start:"
            grep "id = " ~/.config/RustDesk/RustDesk*.toml || echo "ID still not found."

            echo "Setup complete. RustDesk attempted to start in background."
            echo "Container will now sleep indefinitely (or until job timeout/cancellation)."
            echo "Look for RustDesk ID/Password details above."
            echo "-----------------------------------------------------"
            sleep infinity
            '
          # No explicit 'shell:' needed here unless required for the outer step
